In [1]:
import pandas as pd

ruta_archivo = '../data/ventas_brutas.csv'
df = pd.read_csv(ruta_archivo)

df.head()

,ID_Orden,Producto,Cantidad,Fecha_Compra,Direccion,Precio_Unitario
0,1000,Monitor 4K,4,2025-10-21 13:27:00,Sevilla,399
1,1001,Teclado Mecánico,2,2025-04-08 23:39:00,Madrid,120
2,1002,Cargador USB-C,3,2025-08-05 00:29:00,Valencia,25
3,1003,Cargador USB-C,2,2025-01-12 06:52:00,Sevilla,25
4,1004,Cargador USB-C,4,2025-11-04 18:52:00,Barcelona,25

In [2]:
nulos_por_columna = df.isnull().sum()
print("Valores faltantes por columna:")
print(nulos_por_columna)

Valores faltantes por columna:
ID_Orden             0
Producto           487
Cantidad             0
Fecha_Compra         0
Direccion            0
Precio_Unitario      0
dtype: int64

In [4]:
df = df.dropna(how='any')

print(f"filas resultantes: {len(df)}")

filas resultantes: 9513

In [6]:
df['Fecha_Compra'] = pd.to_datetime(df['Fecha_Compra'])

df['Mes'] = df['Fecha_Compra'].dt.month

df['Venta_Total'] = df['Cantidad'] * df['Precio_Unitario']

df.head()

,ID_Orden,Producto,Cantidad,Fecha_Compra,Direccion,Precio_Unitario,Mes,Venta_Total
0,1000,Monitor 4K,4,2025-10-21 13:27:00,Sevilla,399,10,1596
1,1001,Teclado Mecánico,2,2025-04-08 23:39:00,Madrid,120,4,240
2,1002,Cargador USB-C,3,2025-08-05 00:29:00,Valencia,25,8,75
3,1003,Cargador USB-C,2,2025-01-12 06:52:00,Sevilla,25,1,50
4,1004,Cargador USB-C,4,2025-11-04 18:52:00,Barcelona,25,11,100

In [7]:
df.to_csv('../data/ventas_limpias.csv', index=False)
print("Archivo 'Ventas_Limpias' creado con exito!")

Archivo 'Ventas_Limpias' creado con exito!